// Code generated by "stringer -type=Size"; DO NOT EDIT

package bottle

import "fmt"

const _Size_name = "UNKNOWNHALFBOTTLEHALFLITERJURABOTTLEBOTTLEMAGNUMJEROBOAMMETHUSELAHSALMANAZARBALTHAZARNABUCHADNEZZAR"

var _Size_map = map[Size]string{
	0:    _Size_name[0:7],
	37:   _Size_name[7:17],
	50:   _Size_name[17:26],
	62:   _Size_name[26:36],
	75:   _Size_name[36:42],
	150:  _Size_name[42:48],
	300:  _Size_name[48:56],
	600:  _Size_name[56:66],
	1200: _Size_name[66:76],
	1800: _Size_name[76:85],
	2400: _Size_name[85:99],
}

func (i Size) String() string {
	if str, ok := _Size_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Size(%d)", i)
}
