// Code generated by "stringer -type=Color"; DO NOT EDIT

package wine

import "fmt"

const _Color_name = "REDWHITEROSE"

var _Color_index = [...]uint8{0, 3, 8, 12}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return fmt.Sprintf("Color(%d)", i)
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
