// Code generated by "stringer -type=Size"; DO NOT EDIT

package wine

import "fmt"

const (
	_Size_name_0 = "BOTTLEMAGNUM"
	_Size_name_1 = "JEROBOAM"
	_Size_name_2 = "METHUSELAH"
	_Size_name_3 = "SALMANAZAR"
	_Size_name_4 = "BALTHAZAR"
	_Size_name_5 = "NABUCHADNEZZAR"
)

var (
	_Size_index_0 = [...]uint8{0, 6, 12}
	_Size_index_1 = [...]uint8{0, 8}
	_Size_index_2 = [...]uint8{0, 10}
	_Size_index_3 = [...]uint8{0, 10}
	_Size_index_4 = [...]uint8{0, 9}
	_Size_index_5 = [...]uint8{0, 14}
)

func (i Size) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Size_name_0[_Size_index_0[i]:_Size_index_0[i+1]]
	case i == 4:
		return _Size_name_1
	case i == 8:
		return _Size_name_2
	case i == 12:
		return _Size_name_3
	case i == 16:
		return _Size_name_4
	case i == 20:
		return _Size_name_5
	default:
		return fmt.Sprintf("Size(%d)", i)
	}
}
