name: Deploy

on:
  push:
    branches:
    - frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Google Cloud Auth
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: Deploy
      uses: actions/gcloud/cli@master
      with:
        args: app deploy --quiet --project=cave-inventaire
