name: Deploy

on:
  push:
    branches:
    - frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Google Cloud Auth
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_email: ${{ secrets.GCLOUD_EMAIL }}
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
    - name: Deploy
      run: |
        gcloud app deploy --quiet --project ${{ secrets.PROJECT_ID }}
