name: Pull Requests Checks

on: 
  pull_request:
    branches:
    - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Get dependencies
      run: |
        go get -v -d ./...
    - name: Test
      run: go test ./...
