name: Pull Requests Checks

on: 
  pull_request:
    branches:
    - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Go 1.14
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.14
    - name: Get dependencies
      run: go mod download
    - name: Test
      run: go test ./...
